"""Generated smoke tests for all vault distributions — do not edit by hand."""

from __future__ import annotations

import subprocess
from pathlib import Path

import numpy as np
import pytest

import cydist

ROOT = Path(__file__).resolve().parents[1]
RUN_BENCH = ROOT / "build" / "run_bench"

BENCH_IDS: list[str] = [
    "benford",
    "bernoulli",
    "beta-binomial",
    "binomial",
    "categorical",
    "hypergeometric",
    "negative-hypergeometric",
    "poisson-binomial",
    "rademacher",
    "soliton",
    "discrete-uniform",
    "zipf",
    "zipfmandelbrot",
    "beta-negative-binomial",
    "borel",
    "conwaymaxwellpoisson",
    "discrete-phase-type",
    "delaporte",
    "extended-negative-binomial",
    "floryschulz",
    "gausskuzmin",
    "geometric",
    "logarithmic",
    "mixed-poisson",
    "negative-binomial",
    "panjer",
    "parabolic-fractal",
    "poisson",
    "skellam",
    "yulesimon",
    "zeta",
    "arcsine",
    "argus",
    "baldingnichols",
    "bates",
    "beta",
    "generalized-beta",
    "beta-rectangular",
    "continuous-bernoulli",
    "continuous-binomial",
    "irwinhall",
    "kumaraswamy",
    "logit-normal",
    "noncentral-beta",
    "pert",
    "raised-cosine",
    "reciprocal",
    "triangular",
    "u-quadratic",
    "uniform",
    "wigner-semicircle",
    "benini",
    "benktander-1st-kind",
    "benktander-2nd-kind",
    "beta-prime",
    "burr",
    "chi",
    "chi-squared",
    "noncentral-chi-squared",
    "inverse-chi-squared",
    "scaled-inverse-chi-squared",
    "dagum",
    "davis",
    "erlang",
    "hyper",
    "exponential",
    "hyperexponential",
    "hypoexponential",
    "exponential-logarithmic",
    "f",
    "noncentral-f",
    "folded-normal",
    "frechet",
    "gamma",
    "generalized-gamma",
    "inverse-gamma",
    "gamma-gompertz",
    "gompertz",
    "shifted",
    "half-logistic",
    "half-normal",
    "hotellings-t-squared",
    "hartmanwatson",
    "inverse-gaussian",
    "generalized",
    "kolmogorov",
    "levy",
    "log-cauchy",
    "log-laplace",
    "log-logistic",
    "log-normal",
    "log-t",
    "lomax",
    "matrix-exponential",
    "maxwellboltzmann",
    "maxwelljuttner",
    "mittag-leffler",
    "nakagami",
    "pareto",
    "phase-type",
    "poly-weibull",
    "rayleigh",
    "relativistic-breitwigner",
    "rice",
    "truncated-normal",
    "type-2-gumbel",
    "weibull",
    "discrete-weibull",
    "wilkss-lambda",
    "cauchy",
    "exponential-power",
    "fishers-z",
    "kaniadakis-gaussian",
    "gaussian-q",
    "generalized-hyperbolic",
    "generalized-logistic-logistic-beta",
    "generalized-normal",
    "geometric-stable",
    "gumbel",
    "holtsmark",
    "hyperbolic-secant",
    "johnsons-su",
    "landau",
    "laplace",
    "asymmetric",
    "logistic",
    "noncentral-t",
    "normal",
    "normal-inverse-gaussian",
    "skew-normal",
    "slash",
    "stable",
    "student-t",
    "tracywidom",
    "variance-gamma",
    "voigt",
    "generalized-chi-squared",
    "generalized-extreme-value",
    "generalized-pareto",
    "marchenkopastur",
    "kaniadakis-exponential",
    "kaniadakis-gamma",
    "kaniadakis-weibull",
    "kaniadakis-logistic",
    "kaniadakis-erlang",
    "q-exponential",
    "q-gaussian",
    "q-weibull",
    "shifted-log-logistic",
    "tukey-lambda",
    "rectified-gaussian",
    "ewens",
    "multinomial",
    "dirichlet-multinomial",
    "negative-multinomial",
    "dirichlet",
    "generalized-dirichlet",
    "multivariate-laplace",
    "multivariate-normal",
    "multivariate-stable",
    "multivariate-t",
    "normal-gamma",
    "normal-inverse-gamma-distribution",
    "lkj",
    "matrix-beta",
    "matrix-f",
    "matrix-normal",
    "matrix-t",
    "matrix-gamma",
    "inverse-matrix-gamma-distribution",
    "wishart",
    "normal-wishart",
    "inverse-wishart",
    "normal-inverse",
    "complex",
    "uniform-distribution-on-a-stiefel-manifold",
    "circular-uniform",
    "univariate-von-mises",
    "wrapped-normal",
    "wrapped-cauchy",
    "wrapped-exponential",
    "wrapped-asymmetric-laplace",
    "wrapped-levy",
    "kent",
    "bivariate-von-mises",
    "von-misesfisher",
    "bingham",
    "dirac-delta-function",
    "cantor",
]

CYDIST_CASES: list[tuple[str, dict, bool]] = [
    ("benford_sample_batch", {}, True),
    ("bernoulli_sample_batch", {"p": 0.35}, True),
    ("beta_binomial_sample_batch", {"trials": 20, "alpha": 2.0, "beta": 5.0}, True),
    ("binomial_sample_batch", {"trials": 20, "p": 0.4}, True),
    ("categorical_sample_batch", {"probs": np.array([0.5, 0.3, 0.2], dtype=np.float64)}, True),
    ("hypergeometric_sample_batch", {"M": 50, "n_success": 10, "N_draws": 5}, True),
    ("negative_hypergeometric_sample_batch", {"M": 50, "n_": 10, "N": 5}, True),
    ("poisson_binomial_sample_batch", {"probs": np.array([0.1, 0.2, 0.3, 0.4], dtype=np.float64)}, True),
    ("rademacher_sample_batch", {}, True),
    ("soliton_sample_batch", {"loc": 0.0, "scale": 1.0}, True),
    ("discrete_uniform_sample_batch", {"low": 1, "high": 7}, True),
    ("zipf_sample_batch", {"N": 10, "s": 2.0}, True),
    ("zipf_mandelbrot_sample_batch", {"N": 10, "q": 1.0, "s": 2.0}, True),
    ("beta_negative_binomial_sample_batch", {"alpha": 2.0, "beta": 5.0, "r": 1.0}, True),
    ("borel_sample_batch", {"mu": 0.5}, True),
    ("conwaymaxwellpoisson_sample_batch", {"lambda_": 4.0, "nu": 1.0}, True),
    ("discrete_phase_type_sample_batch", {"p1": 0.6, "p2": 0.4}, True),
    ("delaporte_sample_batch", {"lambda_": 1.0, "r": 2.0, "p": 0.5}, True),
    ("extended_negative_binomial_sample_batch", {"r": 5.0, "p": 0.4}, True),
    ("floryschulz_sample_batch", {"p": 0.8}, True),
    ("gausskuzmin_sample_batch", {}, True),
    ("geometric_sample_batch", {"p": 0.25}, True),
    ("logarithmic_sample_batch", {"p": 0.5}, True),
    ("mixed_poisson_sample_batch", {"shape": 2.0, "scale": 1.0}, True),
    ("negative_binomial_sample_batch", {"r": 5, "p": 0.4}, True),
    ("panjer_sample_batch", {"lambda_": 4.0}, True),
    ("parabolic_fractal_sample_batch", {"b": 2.0, "c": 0.1}, True),
    ("poisson_sample_batch", {"mu": 4.0}, True),
    ("skellam_sample_batch", {"mu1": 3.0, "mu2": 1.0}, True),
    ("yulesimon_sample_batch", {"rho": 2.0}, True),
    ("zeta_sample_batch", {"N": 100, "s": 2.0}, True),
    ("arcsine_sample_batch", {}, False),
    ("argus_sample_batch", {"chi": 1.0}, False),
    ("baldingnichols_sample_batch", {"f": 0.1}, False),
    ("bates_sample_batch", {"n_": 4, "lo": 0.0, "hi": 1.0}, False),
    ("beta_sample_batch", {"alpha": 2.0, "beta": 5.0}, False),
    ("generalized_beta_sample_batch", {"alpha": 2.0, "beta": 5.0, "lambda_": 0.0}, False),
    ("beta_rectangular_sample_batch", {"alpha": 2.0, "beta": 5.0}, False),
    ("continuous_bernoulli_sample_batch", {"lambda_": 0.5}, False),
    ("continuous_binomial_sample_batch", {"n_": 10}, False),
    ("irwinhall_sample_batch", {"n_": 4, "lo": 0.0, "hi": 1.0}, False),
    ("kumaraswamy_sample_batch", {"a": 2.0, "b": 5.0}, False),
    ("logit_normal_sample_batch", {"mu": 0.0, "sigma": 1.0}, False),
    ("noncentral_beta_sample_batch", {"alpha": 2.0, "beta": 5.0, "lam": 1.0}, False),
    ("pert_sample_batch", {"lo": 0.0, "mode": 0.5, "hi": 1.0}, False),
    ("raised_cosine_sample_batch", {"lo": 0.0, "hi": 1.0}, False),
    ("reciprocal_sample_batch", {"a": 0.5, "b": 2.0}, False),
    ("triangular_sample_batch", {"lo": 0.0, "mode": 0.5, "hi": 1.0}, False),
    ("u_quadratic_sample_batch", {"a": 0.0, "b": 1.0}, False),
    ("uniform_sample_batch", {"lo": 0.0, "hi": 1.0}, False),
    ("wigner_semicircle_sample_batch", {"lo": -1.0, "scale": 2.0}, False),
    ("benini_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("benktander_1st_kind_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("benktander_2nd_kind_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("beta_prime_sample_batch", {"alpha": 2.0, "beta": 5.0}, False),
    ("burr_sample_batch", {"c": 2.0, "scale": 1.0}, False),
    ("chi_sample_batch", {"df": 3.0}, False),
    ("chi_squared_sample_batch", {"df": 3.0}, False),
    ("noncentral_chi_squared_sample_batch", {"df": 3.0, "ncp": 2.0}, False),
    ("inverse_chi_squared_sample_batch", {"df": 3.0, "scale": 1.0}, False),
    ("scaled_inverse_chi_squared_sample_batch", {"df": 3.0, "scale": 1.0}, False),
    ("dagum_sample_batch", {"c": 2.0, "scale": 1.0}, False),
    ("davis_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("erlang_sample_batch", {"a": 2.0, "scale": 1.0}, False),
    ("hyper_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("exponential_sample_batch", {"rate": 1.0}, False),
    ("hyperexponential_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("hypoexponential_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("exponential_logarithmic_sample_batch", {"scale": 1.0}, False),
    ("f_sample_batch", {"dfn": 5.0, "dfd": 10.0}, False),
    ("noncentral_f_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("folded_normal_sample_batch", {"c": 1.0, "loc": 0.0, "scale": 1.0}, False),
    ("frechet_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("gamma_sample_batch", {"shape": 2.0, "scale": 2.0}, False),
    ("generalized_gamma_sample_batch", {"a": 2.0, "c": 1.0, "scale": 1.0}, False),
    ("inverse_gamma_sample_batch", {"shape": 3.0, "scale": 1.0}, False),
    ("gamma_gompertz_sample_batch", {"shape": 2.0, "scale": 2.0}, False),
    ("gompertz_sample_batch", {"c": 1.0, "scale": 1.0}, False),
    ("shifted_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("half_logistic_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("half_normal_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("hotellings_t_squared_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("hartmanwatson_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("inverse_gaussian_sample_batch", {"mu": 1.0, "lambda_": 1.0}, False),
    ("generalized_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("kolmogorov_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("levy_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("log_cauchy_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("log_laplace_sample_batch", {"c": 1.0, "scale": 1.0}, False),
    ("log_logistic_sample_batch", {"c": 2.0, "scale": 1.0}, False),
    ("log_normal_sample_batch", {"mu": 0.0, "sigma": 0.5}, False),
    ("log_t_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("lomax_sample_batch", {"c": 2.0, "scale": 1.0}, False),
    ("matrix_exponential_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("maxwellboltzmann_sample_batch", {"a": 1.0}, False),
    ("maxwelljuttner_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("mittag_leffler_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("nakagami_sample_batch", {"nu": 2.0, "scale": 1.0}, False),
    ("pareto_sample_batch", {"alpha": 2.0, "scale": 1.0}, False),
    ("phase_type_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("poly_weibull_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("rayleigh_sample_batch", {"scale": 1.5}, False),
    ("relativistic_breitwigner_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("rice_sample_batch", {"b": 0.5, "scale": 1.0}, False),
    ("truncated_normal_sample_batch", {"a": -1.0, "b": 2.0, "loc": 0.0, "scale": 1.0}, False),
    ("type_2_gumbel_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("weibull_sample_batch", {"shape": 1.5, "scale": 2.0}, False),
    ("discrete_weibull_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("wilkss_lambda_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("cauchy_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("exponential_power_sample_batch", {"scale": 1.0}, False),
    ("fishers_z_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("kaniadakis_gaussian_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("gaussian_q_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("generalized_hyperbolic_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("generalized_logistic_logistic_beta_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("generalized_normal_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("geometric_stable_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("gumbel_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("holtsmark_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("hyperbolic_secant_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("johnsons_su_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("landau_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("laplace_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("asymmetric_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("logistic_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("noncentral_t_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("normal_sample_batch", {"mu": 0.0, "sigma": 1.0}, False),
    ("normal_inverse_gaussian_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("skew_normal_sample_batch", {"loc": 0.0, "scale": 1.0, "alpha": 4.0}, False),
    ("slash_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("stable_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("students_t_sample_batch", {"df": 5.0}, False),
    ("tracywidom_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("variance_gamma_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("voigt_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("generalized_chi_squared_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("generalized_extreme_value_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("generalized_pareto_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("marchenkopastur_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("kaniadakis_exponential_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("kaniadakis_gamma_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("kaniadakis_weibull_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("kaniadakis_logistic_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("kaniadakis_erlang_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("q_exponential_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("q_gaussian_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("q_weibull_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("shifted_log_logistic_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("tukey_lambda_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("rectified_gaussian_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("ewens_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("multinomial_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("dirichlet_multinomial_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("negative_multinomial_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("dirichlet_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("generalized_dirichlet_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("multivariate_laplace_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("multivariate_normal_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("multivariate_stable_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("multivariate_t_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("normal_gamma_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("normal_inverse_gamma_distribution_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("lkj_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("matrix_beta_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("matrix_f_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("matrix_normal_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("matrix_t_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("matrix_gamma_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("inverse_matrix_gamma_distribution_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("wishart_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("normal_wishart_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("inverse_wishart_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("normal_inverse_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("complex_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("uniform_distribution_on_a_stiefel_manifold_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("circular_uniform_sample_batch", {"mu": 0.0, "kappa": 0.0}, False),
    ("univariate_von_mises_sample_batch", {"mu": 0.0, "kappa": 2.0}, False),
    ("wrapped_normal_sample_batch", {"mu": 0.0, "sigma": 0.5}, False),
    ("wrapped_cauchy_sample_batch", {"c": 0.5, "loc": 0.0, "scale": 1.0}, False),
    ("wrapped_exponential_sample_batch", {"loc": 0.0, "rate": 1.0}, False),
    ("wrapped_asymmetric_laplace_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("wrapped_levy_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("kent_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("bivariate_von_mises_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("von_misesfisher_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("bingham_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
    ("dirac_delta_function_sample_batch", {"x0": 0.0}, False),
    ("cantor_sample_batch", {"loc": 0.0, "scale": 1.0}, False),
]

def test_cydist_export_count() -> None:
    assert len(cydist.__all__) == 189


@pytest.mark.parametrize("dist_id", BENCH_IDS)
def test_cpp_run_bench(dist_id: str) -> None:
    assert RUN_BENCH.exists(), "run make build first"
    subprocess.run(
        [str(RUN_BENCH), dist_id, "cpp", "1000", "42", "--csv"],
        check=True,
        cwd=ROOT,
    )


@pytest.mark.parametrize("func_name,kwargs,discrete", CYDIST_CASES)
def test_cydist_sample_batch(func_name: str, kwargs: dict, discrete: bool) -> None:
    fn = getattr(cydist, func_name)
    dtype = np.int32 if discrete else np.float64
    out = np.zeros(128, dtype=dtype)
    fn(out, seed=42, **kwargs)
    if discrete:
        assert out.size == 128
    else:
        assert np.all(np.isfinite(out))
