"""Code generators: headers, dispatch, cydist, tests, registry."""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
VAULT_TOOLS = ROOT / ".vault" / "tools"
sys.path.insert(0, str(VAULT_TOOLS))

from codegen.constants import (
    BENCH,
    BENCH_ALIAS,
    C_FUNC_ALIASES,
    CYDIST,
    FUSED_CONTINUOUS_VAULT_IDS,
    FUSED_FLOAT_CPP_CLASS,
    INCLUDE,
    MANUAL,
    MANUAL_CPP_CLASS,
    PY_FUNC_ALIASES,
)
from codegen.models import CydistSpec, Recipe
from codegen.utils import safe_param_name, slug_to_class

def emit_header(r: Recipe) -> str:
    ctor_params = ", ".join(f"{t} {n}" for t, n, _ in r.members)
    init_list = ", ".join(f"{n}_({n})" for _, n, _ in r.members) if r.members else ""
    includes = sorted(set(["distributions/rng.hpp", *r.includes]))
    inc_lines = "\n".join(f'#include "{h}"' for h in includes)
    out_type = "int" if r.discrete else "double"
    extra = "#include <numbers>\n" if "std::numbers" in r.sample_body else ""
    if any(
        tok in r.sample_body
        for tok in ("std::log", "std::pow", "std::sqrt", "std::fmod", "std::acos", "std::cos")
    ):
        extra += "#include <cmath>\n"
    extra += "#include <cstddef>\n"

    if init_list:
        ctor = f"    {r.cpp_class}({ctor_params}) : {init_list} {{}}\n"
        members_decl = "\n".join(f"    {t} {n}_;" for t, n, _ in r.members)
    else:
        ctor = f"    {r.cpp_class}() = default;\n"
        members_decl = ""

    return f"""#pragma once

{inc_lines}
{extra}
namespace distributions {{

struct {r.cpp_class} {{
{members_decl}
{ctor}
    [[nodiscard]] {out_type} sample(Pcg32& rng) const {{
        {r.sample_body}
    }}

    void sample_batch({out_type}* out, std::size_t n, Pcg32& rng) const {{
        for (std::size_t i = 0; i < n; ++i) {{
            out[i] = sample(rng);
        }}
    }}
}};

}}  // namespace distributions
"""


def python_func_name(vault_id: str) -> str:
    if vault_id in PY_FUNC_ALIASES:
        return PY_FUNC_ALIASES[vault_id]
    return vault_id.replace("-", "_") + "_sample_batch"


def c_func_name(vault_id: str) -> str:
    if vault_id in C_FUNC_ALIASES:
        return C_FUNC_ALIASES[vault_id]
    return "cydist_" + vault_id.replace("-", "_") + "_sample_batch"


def _one_line(text: str, max_len: int = 100) -> str:
    cleaned = " ".join(text.split())
    if len(cleaned) > max_len:
        cleaned = cleaned[: max_len - 3].rstrip() + "..."
    return cleaned.replace('"', "'")


def _dtype_label(discrete: bool) -> str:
    return "int32" if discrete else "float64"


def _func_docstring(spec: CydistSpec) -> str:
    summary = _one_line(spec.summary or f"{spec.name} distribution.")
    tier = f" Tier: {spec.sampler_tier}." if spec.sampler_tier == "heuristic" else ""
    return (
        f"Sample {spec.name} into ``out`` ({_dtype_label(spec.discrete)}). "
        f"{summary}{tier}"
    )


def _category_banner(category_path: str) -> str:
    return f"# --- {category_path.replace('/', ' / ')} ---"


CYDIST_MODULE_DOC = '''"""Fast batch samplers for probability distributions (C++/Cython).

Pre-allocate ``out`` and pass it to ``*_sample_batch``; samples are written in-place.
Discrete distributions use ``int32`` arrays; continuous use ``float64`` (default) or
``float32`` for normal and exponential (Cython ``FusedType`` dispatch).
The GIL is released during each call. RNG: PCG32 via ``seed`` (default 42).
"""'''

CYDIST_PYX_MODULE_DOC = '''"""Cython batch samplers for all vault distributions (generated).

Pre-allocated NumPy ``out`` is filled in-place; GIL released per call.
Discrete → int32; continuous → float64 (or float32 for normal/exponential via FusedType).
RNG: PCG32 (``seed``, default 42).
"""'''

CYDIST_PXD_HEADER = """# dist: ignore
# Generated by tools/codegen — do not edit by hand.
#
# Declarations for cydist_shim.h ({n} nogil batch samplers).
# Included from cydist.pyx; cimport for downstream Cython extensions.
"""


def build_cydist_specs(registry: list[dict], recipes: dict[str, Recipe]) -> list[CydistSpec]:
    manual_params: dict[str, list[tuple[str, str, str]]] = {
        "bernoulli": [("p", "double", "scalar_double")],
        "discrete-uniform": [
            ("low", "int", "scalar_int"),
            ("high", "int", "scalar_int"),
        ],
        "binomial": [("trials", "int", "scalar_int"), ("p", "double", "scalar_double")],
        "geometric": [("p", "double", "scalar_double")],
        "exponential": [("rate", "double", "scalar_double")],
        "normal-gaussian": [("mu", "double", "scalar_double"), ("sigma", "double", "scalar_double")],
        "categorical": [("probs", "const double*", "probs")],
        "skellam": [("mu1", "double", "scalar_double"), ("mu2", "double", "scalar_double")],
        "poisson-binomial": [("probs", "const double*", "probs")],
        "beta-binomial": [
            ("trials", "int", "scalar_int"),
            ("alpha", "double", "scalar_double"),
            ("beta", "double", "scalar_double"),
        ],
        "negative-binomial": [("r", "int", "scalar_int"), ("p", "double", "scalar_double")],
        "zipf": [("N", "int", "scalar_int"), ("s", "double", "scalar_double")],
        "zipfmandelbrot": [
            ("N", "int", "scalar_int"),
            ("q", "double", "scalar_double"),
            ("s", "double", "scalar_double"),
        ],
    }

    specs: list[CydistSpec] = []
    for entry in registry:
        vid = entry["id"]
        discrete = entry.get("type") == "discrete"
        meta = dict(
            name=entry.get("name", vid),
            category_path=entry.get("category_path", "unknown"),
            summary=entry.get("summary") or "",
            sampler_tier="hand-written" if vid in MANUAL else recipes[vid].sampler_tier,
        )

        if vid in MANUAL_CPP_CLASS:
            specs.append(
                CydistSpec(
                    vault_id=vid,
                    py_func=python_func_name(vid),
                    c_func=c_func_name(vid),
                    cpp_class=MANUAL_CPP_CLASS[vid],
                    discrete=discrete,
                    params=manual_params[vid],
                    **meta,
                )
            )
            continue

        r = recipes[vid]
        params: list[tuple[str, str, str]] = []
        for ctype, name, _default in r.members:
            if ctype == "int":
                params.append((name, "int", "scalar_int"))
            else:
                params.append((name, "double", "scalar_double"))
        specs.append(
            CydistSpec(
                vault_id=vid,
                py_func=python_func_name(vid),
                c_func=c_func_name(vid),
                cpp_class=r.cpp_class,
                discrete=r.discrete,
                params=params,
                **meta,
            )
        )
    return specs


def _cydist_ctor_body(
    spec: CydistSpec, ctor_args: list[str], shim_body_prefix: list[str], cpp_class: str
) -> list[str]:
    if shim_body_prefix:
        return shim_body_prefix
    if ctor_args:
        return [f"    distributions::{cpp_class} dist({', '.join(ctor_args)});"]
    return [f"    distributions::{cpp_class} dist;"]


def _append_cydist_shim(
    *,
    c_func: str,
    c_params: list[str],
    body: list[str],
    shim_decls: list[str],
    shim_impl: list[str],
) -> None:
    shim_decls.append(f"void {c_func}({', '.join(c_params)});")
    shim_impl.append(f"void {c_func}({', '.join(c_params)}) {{")
    shim_impl.extend(body)
    shim_impl.append("    distributions::Pcg32 rng(seed);")
    shim_impl.append("    dist.sample_batch(out, n_samples, rng);")
    shim_impl.append("}")
    shim_impl.append("")


def emit_cydist(specs: list[CydistSpec]) -> None:
    shim_decls: list[str] = []
    shim_impl: list[str] = []
    pyx_extern: list[str] = []
    pyx_funcs: list[str] = []
    py_exports: list[str] = []
    pyi_lines: list[str] = [CYDIST_MODULE_DOC, "", "import numpy as np", ""]

    prev_category: str | None = None
    for spec in specs:
        if spec.category_path != prev_category:
            if prev_category is not None:
                pyx_funcs.append("")
            pyx_funcs.append(_category_banner(spec.category_path))
            pyx_funcs.append("")
            prev_category = spec.category_path

        out_c = "int" if spec.discrete else "double"
        fused_continuous = spec.vault_id in FUSED_CONTINUOUS_VAULT_IDS and not spec.discrete
        out_pyx = "cnp.int32_t" if spec.discrete else ("ContinuousOut" if fused_continuous else "cnp.float64_t")

        c_params: list[str] = []
        pyx_sig_params: list[str] = [f"{out_pyx}[:] out"]
        py_sig_params: list[str] = ["out: np.ndarray"]
        ctor_args: list[str] = []
        shim_body_prefix: list[str] = []

        for name, c_type, kind in spec.params:
            safe = safe_param_name(name)
            if kind == "probs":
                c_params.append(f"const double* {safe}")
                c_params.append("int k")
                pyx_sig_params.append("cnp.float64_t[:] probs")
                py_sig_params.append("probs: np.ndarray")
                shim_body_prefix = [
                    f"    std::vector<double> pv({safe}, {safe} + k);",
                    f"    distributions::{spec.cpp_class} dist(std::move(pv));",
                ]
            elif kind == "scalar_int":
                c_params.append(f"int {safe}")
                pyx_sig_params.append(f"int {safe}")
                py_sig_params.append(f"{safe}: int")
                ctor_args.append(safe)
            else:
                c_params.append(f"double {safe}")
                pyx_sig_params.append(f"double {safe}")
                py_sig_params.append(f"{safe}: float")
                ctor_args.append(safe)

        c_params += ["uint64_t seed", f"{out_c}* out", "size_t n_samples"]
        pyx_sig_params.append("uint64_t seed=42")
        py_sig_params.append("seed: int = 42")

        body = _cydist_ctor_body(spec, ctor_args, shim_body_prefix, spec.cpp_class)
        _append_cydist_shim(
            c_func=spec.c_func,
            c_params=c_params,
            body=body,
            shim_decls=shim_decls,
            shim_impl=shim_impl,
        )

        if fused_continuous:
            c_func_f32 = f"{spec.c_func}_f32"
            float_cpp = FUSED_FLOAT_CPP_CLASS[spec.vault_id]
            c_params_f32 = c_params[:-3] + ["uint64_t seed", "float* out", "size_t n_samples"]
            body_f32 = _cydist_ctor_body(spec, ctor_args, shim_body_prefix, float_cpp)
            _append_cydist_shim(
                c_func=c_func_f32,
                c_params=c_params_f32,
                body=body_f32,
                shim_decls=shim_decls,
                shim_impl=shim_impl,
            )

        pyx_c_params: list[str] = []
        for name, c_type, kind in spec.params:
            safe = safe_param_name(name)
            if kind == "probs":
                pyx_c_params.append(f"const double* {safe}")
                pyx_c_params.append("int k")
            else:
                pyx_c_params.append(f"{c_type} {safe}")
        pyx_c_params += ["uint64_t seed", f"{out_c}* out", "size_t n_samples"]
        pyx_extern.append(
            f"    void {spec.c_func}({', '.join(pyx_c_params)}) nogil"
        )
        if fused_continuous:
            pyx_c_params_f32 = pyx_c_params[:-3] + ["uint64_t seed", "float* out", "size_t n_samples"]
            pyx_extern.append(
                f"    void {c_func_f32}({', '.join(pyx_c_params_f32)}) nogil"
            )

        call_args: list[str] = []
        setup: list[str] = ["    cdef size_t n_samples = <size_t>out.shape[0]"]
        for name, _c_type, kind in spec.params:
            safe = safe_param_name(name)
            if kind == "probs":
                setup.append("    cdef const double* probs_ptr = <const double*>&probs[0]")
                setup.append("    cdef int k = <int>probs.shape[0]")
                call_args.extend(["probs_ptr", "k"])
            else:
                call_args.append(safe)

        pyx_funcs.append(f"def {spec.py_func}({', '.join(pyx_sig_params)}):")
        if fused_continuous:
            setup.extend(
                [
                    "    cdef float* ptr_f32",
                    "    cdef double* ptr_f64",
                ]
            )
            pyx_funcs.extend(setup)
            call_f64 = call_args + ["seed", "ptr_f64", "n_samples"]
            call_f32 = call_args + ["seed", "ptr_f32", "n_samples"]
            pyx_funcs.append("    if ContinuousOut is cnp.float32_t:")
            pyx_funcs.append("        ptr_f32 = &out[0]")
            pyx_funcs.append("        with nogil:")
            pyx_funcs.append(f"            {c_func_f32}({', '.join(call_f32)})")
            pyx_funcs.append("    else:")
            pyx_funcs.append("        ptr_f64 = &out[0]")
            pyx_funcs.append("        with nogil:")
            pyx_funcs.append(f"            {spec.c_func}({', '.join(call_f64)})")
        else:
            setup.append(f"    cdef {out_c}* ptr = <{out_c}*>&out[0]")
            pyx_funcs.extend(setup)
            call_args.extend(["seed", "ptr", "n_samples"])
            pyx_funcs.append("    with nogil:")
            pyx_funcs.append(f"        {spec.c_func}({', '.join(call_args)})")
        pyx_funcs.append("")

        py_exports.append(spec.py_func)
        doc = _func_docstring(spec)
        if fused_continuous:
            doc += " Accepts float32 or float64 ``out`` (FusedType dispatch)."
        pyi_lines.append(f"def {spec.py_func}({', '.join(py_sig_params)}) -> None:")
        pyi_lines.append(f'    """{doc}"""')
        pyi_lines.append("")

    (CYDIST / "cydist_shim.h").write_text(
        "#pragma once\n// Generated by tools/codegen_distributions.py\n\n"
        "#include <stddef.h>\n#include <stdint.h>\n\n"
        "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"
        + "\n".join(shim_decls)
        + "\n\n#ifdef __cplusplus\n}\n#endif\n"
    )

    (CYDIST / "cydist_shim.cpp").write_text(
        "// Generated by tools/codegen_distributions.py\n"
        '#include "distributions/all.hpp"\n\n'
        "#include <cstddef>\n#include <cstdint>\n#include <vector>\n\n"
        "extern \"C\" {\n\n"
        + "\n".join(shim_impl)
        + "}  // extern \"C\"\n"
    )

    (CYDIST / "cydist.pyx").write_text(
        "# cython: language_level=3\n"
        + CYDIST_PYX_MODULE_DOC
        + "\n"
        "cimport numpy as cnp\n"
        "from libc.stddef cimport size_t\n"
        "from libc.stdint cimport uint64_t\n\n"
        "cnp.import_array()\n\n"
        + (
            "ctypedef fused ContinuousOut:\n"
            "    cnp.float32_t\n"
            "    cnp.float64_t\n\n"
            if any(s.vault_id in FUSED_CONTINUOUS_VAULT_IDS for s in specs)
            else ""
        )
        + 'cdef extern from "cydist_shim.h":\n'
        + "\n".join(pyx_extern)
        + "\n\n"
        + "\n".join(pyx_funcs)
    )

    init_exports = ",\n    ".join(py_exports)
    (CYDIST / "__init__.py").write_text(
        '"""Python bindings for distribution samplers."""\n\n'
        "from cydist._native import (\n    "
        + ",\n    ".join(py_exports)
        + ",\n)\n\n"
        f"__all__: list[str] = [\n    {init_exports},\n]\n"
    )

    pyi_lines.append("__all__: list[str] = [")
    pyi_lines.extend(f'    "{name}",' for name in py_exports)
    pyi_lines.append("]")
    (CYDIST / "__init__.pyi").write_text("\n".join(pyi_lines) + "\n")

    pxd_lines = [
        CYDIST_PXD_HEADER.format(n=len(specs)).rstrip(),
        "from libc.stdint cimport uint64_t",
        "from libc.stddef cimport size_t",
        "",
        'cdef extern from "cydist_shim.h":',
        *pyx_extern,
    ]
    (CYDIST / "cydist.pxd").write_text("\n".join(pxd_lines) + "\n")


def emit_registry_tiers(registry: list[dict], recipes: dict[str, Recipe]) -> None:
    """Write sampler_tier into registry.yaml for each distribution."""
    path = ROOT / ".vault" / "_meta" / "registry.yaml"
    data = yaml.safe_load(path.read_text())
    for entry in data["distributions"]:
        vid = entry["id"]
        if vid in MANUAL:
            entry["sampler_tier"] = "hand-written"
        elif vid in recipes:
            entry["sampler_tier"] = recipes[vid].sampler_tier
        else:
            entry["sampler_tier"] = "family"
    path.write_text(yaml.dump(data, sort_keys=False, allow_unicode=True, default_flow_style=False))
    tiers = {e["sampler_tier"] for e in data["distributions"]}
    print(f"  registry: sampler_tier updated ({', '.join(sorted(tiers))})")


MANUAL_PY_KWARGS: dict[str, str] = {
    "bernoulli": '{"p": 0.35}',
    "discrete-uniform": '{"low": 1, "high": 7}',
    "binomial": '{"trials": 20, "p": 0.4}',
    "geometric": '{"p": 0.25}',
    "exponential": '{"rate": 1.0}',
    "normal-gaussian": '{"mu": 0.0, "sigma": 1.0}',
    "categorical": '{"probs": np.array([0.5, 0.3, 0.2], dtype=np.float64)}',
    "skellam": '{"mu1": 3.0, "mu2": 1.0}',
    "poisson-binomial": '{"probs": np.array([0.1, 0.2, 0.3, 0.4], dtype=np.float64)}',
    "beta-binomial": '{"trials": 20, "alpha": 2.0, "beta": 5.0}',
    "negative-binomial": '{"r": 5, "p": 0.4}',
    "zipf": '{"N": 10, "s": 2.0}',
    "zipfmandelbrot": '{"N": 10, "q": 1.0, "s": 2.0}',
}


def py_kwargs_literal(spec: CydistSpec, recipe: Recipe | None) -> str:
    if spec.vault_id in MANUAL_PY_KWARGS:
        return MANUAL_PY_KWARGS[spec.vault_id]
    if recipe is None or not recipe.bench_ctor_args:
        return "{}"
    vals = [v.strip() for v in recipe.bench_ctor_args.split(",")]
    parts: list[str] = []
    for (pname, _, kind), val in zip(spec.params, vals, strict=False):
        pyname = safe_param_name(pname)
        if kind == "scalar_int":
            parts.append(f'"{pyname}": {int(float(val))}')
        else:
            parts.append(f'"{pyname}": {float(val)}')
    return "{" + ", ".join(parts) + "}"


def emit_tests(registry: list[dict], recipes: dict[str, Recipe], specs: list[CydistSpec]) -> None:
    alias = {"normal-gaussian": "normal", "students-t": "student-t"}
    bench_ids: list[str] = []
    seen: set[str] = set()
    for entry in registry:
        bench_id = alias.get(entry["id"], entry["id"])
        if bench_id in seen:
            continue
        seen.add(bench_id)
        bench_ids.append(bench_id)

    cydist_cases: list[str] = []
    for spec in specs:
        recipe = recipes.get(spec.vault_id)
        kwargs = py_kwargs_literal(spec, recipe)
        cydist_cases.append(
            f'    ("{spec.py_func}", {kwargs}, {spec.discrete!r}),'
        )

    tests_dir = ROOT / "tests"
    tests_dir.mkdir(exist_ok=True)
    (tests_dir / "test_generated.py").write_text(
        '"""Generated smoke tests for all vault distributions — do not edit by hand."""\n\n'
        "from __future__ import annotations\n\n"
        "import subprocess\n"
        "from pathlib import Path\n\n"
        "import numpy as np\n"
        "import pytest\n\n"
        "import cydist\n\n"
        f"ROOT = Path(__file__).resolve().parents[1]\n"
        f"RUN_BENCH = ROOT / \"build\" / \"run_bench\"\n\n"
        f"BENCH_IDS: list[str] = [\n"
        + "\n".join(f'    "{bid}",' for bid in bench_ids)
        + "\n]\n\n"
        f"CYDIST_CASES: list[tuple[str, dict, bool]] = [\n"
        + "\n".join(cydist_cases)
        + "\n]\n\n"
        "def test_cydist_export_count() -> None:\n"
        f"    assert len(cydist.__all__) == {len(specs)}\n\n\n"
        "@pytest.mark.parametrize(\"dist_id\", BENCH_IDS)\n"
        "def test_cpp_run_bench(dist_id: str) -> None:\n"
        "    assert RUN_BENCH.exists(), \"run make build first\"\n"
        "    subprocess.run(\n"
        "        [str(RUN_BENCH), dist_id, \"cpp\", \"1000\", \"42\", \"--csv\"],\n"
        "        check=True,\n"
        "        cwd=ROOT,\n"
        "    )\n\n\n"
        "@pytest.mark.parametrize(\"func_name,kwargs,discrete\", CYDIST_CASES)\n"
        "def test_cydist_sample_batch(func_name: str, kwargs: dict, discrete: bool) -> None:\n"
        "    fn = getattr(cydist, func_name)\n"
        "    dtype = np.int32 if discrete else np.float64\n"
        "    out = np.zeros(128, dtype=dtype)\n"
        "    fn(out, seed=42, **kwargs)\n"
        "    if discrete:\n"
        "        assert out.size == 128\n"
        "    else:\n"
        "        assert np.all(np.isfinite(out))\n"
    )
    print(f"  tests: {len(bench_ids)} C++ + {len(specs)} Python smoke tests")


