"""Orchestration for full library codegen."""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
VAULT_TOOLS = ROOT / ".vault" / "tools"
sys.path.insert(0, str(VAULT_TOOLS))

from codegen.constants import BENCH, BENCH_ALIAS, INCLUDE, MANUAL
from codegen.emit import (
    build_cydist_specs,
    emit_cydist,
    emit_header,
    emit_registry_batch_fast,
    emit_registry_tiers,
    emit_tests,
)
from codegen.models import Recipe
from codegen.recipes import assign_sampler_tiers, build_recipes
from codegen.utils import slug_to_class

def emit_all(registry: list[dict], recipes: dict[str, Recipe]) -> None:
    # Move manual files first (caller responsibility); generate new headers.
    generated_paths: list[str] = []
    for entry in registry:
        vid = entry["id"]
        if vid in MANUAL:
            generated_paths.append(MANUAL[vid])
            continue
        r = recipes[vid]
        rel = f"{r.folder}/{vid.replace('-', '_')}.hpp"
        path = INCLUDE / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(emit_header(r))
        generated_paths.append(rel)

    # all.hpp
    lines = ["#pragma once", "// Generated by tools/codegen_distributions.py — do not edit by hand.", ""]
    for rel in sorted(set(generated_paths)):
        lines.append(f'#include "distributions/{rel}"')
    (INCLUDE / "all.hpp").write_text("\n".join(lines) + "\n")

    # dispatch metadata + sample_cpp
    dist_specs: list[tuple[str, bool, str]] = []
    for entry in registry:
        vid = entry["id"]
        bench_id = BENCH_ALIAS.get(vid, vid)
        discrete = entry.get("type") == "discrete"
        if vid in MANUAL:
            if vid == "normal-gaussian":
                ctor = "const distributions::Normal d(0.0, 1.0)"
            elif vid == "zipfmandelbrot":
                ctor = "const distributions::ZipfMandelbrot d(10, 1.0, 2.0)"
            elif vid == "discrete-uniform":
                ctor = "const distributions::DiscreteUniform d(1, 7)"
            elif vid == "bernoulli":
                ctor = "const distributions::Bernoulli d(0.35)"
            elif vid == "binomial":
                ctor = "const distributions::Binomial d(20, 0.4)"
            elif vid == "geometric":
                ctor = "const distributions::Geometric d(0.25)"
            elif vid == "exponential":
                ctor = "const distributions::Exponential d(1.0)"
            elif vid == "categorical":
                ctor = "const distributions::Categorical d({0.5, 0.3, 0.2})"
            elif vid == "skellam":
                ctor = "const distributions::Skellam d(3.0, 1.0)"
            elif vid == "poisson-binomial":
                ctor = "const distributions::PoissonBinomial d({0.1, 0.2, 0.3, 0.4})"
            elif vid == "beta-binomial":
                ctor = "const distributions::BetaBinomial d(20, 2.0, 5.0)"
            elif vid == "negative-binomial":
                ctor = "const distributions::NegativeBinomial d(5, 0.4)"
            elif vid == "zipf":
                ctor = "const distributions::Zipf d(10, 2.0)"
            else:
                cls = slug_to_class(vid)
                ctor = f"const distributions::{cls} d"
            cls = ctor  # dispatch uses ctor directly
        else:
            r = recipes[vid]
            cls = r.cpp_class
            if r.bench_ctor_args:
                ctor = f"const distributions::{cls} d({r.bench_ctor_args})"
            else:
                ctor = f"const distributions::{cls} d"
        dist_specs.append((bench_id, discrete, ctor))

    dispatch_cpp = []
    for bench_id, discrete, ctor in dist_specs:
        if discrete:
            dispatch_cpp.append(f'''    if (dist == "{bench_id}") {{
        {ctor};
        out_i.resize(n);
        d.sample_batch(out_i.data(), n, rng);
        return;
    }}''')
        else:
            dispatch_cpp.append(f'''    if (dist == "{bench_id}") {{
        {ctor};
        out_d.resize(n);
        d.sample_batch(out_d.data(), n, rng);
        return;
    }}''')

    spec_lines = []
    for bench_id, discrete, _ in dist_specs:
        spec_lines.append(f'        {{"{bench_id}", {str(discrete).lower()}}},')

    dispatch = f'''#pragma once
// Generated by tools/codegen_distributions.py — do not edit by hand.

#include "distributions/all.hpp"

#include <cstdint>
#include <cstring>
#include <fstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace bench {{

struct DistSpec {{
    std::string id;
    bool discrete{{true}};
}};

inline const std::vector<DistSpec>& all_dists() {{
    static const std::vector<DistSpec> k = {{
{chr(10).join(spec_lines)}
    }};
    return k;
}}

inline void sample_cpp(
    const std::string& dist,
    std::uint64_t seed,
    std::size_t n,
    std::vector<int>& out_i,
    std::vector<double>& out_d) {{
    distributions::Pcg32 rng(seed);
{chr(10).join(dispatch_cpp)}
    throw std::runtime_error("unknown dist: " + dist);
}}

inline void write_samples_binary(
    const std::string& path,
    bool discrete,
    const std::vector<int>& out_i,
    const std::vector<double>& out_d) {{
    std::ofstream f(path, std::ios::binary);
    if (!f) {{
        throw std::runtime_error("cannot open " + path);
    }}
    const char tag = discrete ? 'i' : 'd';
    f.write(&tag, 1);
    const std::uint64_t n = discrete ? out_i.size() : out_d.size();
    f.write(reinterpret_cast<const char*>(&n), sizeof(n));
    if (discrete) {{
        f.write(reinterpret_cast<const char*>(out_i.data()), static_cast<std::streamsize>(n * sizeof(int)));
    }} else {{
        f.write(reinterpret_cast<const char*>(out_d.data()), static_cast<std::streamsize>(n * sizeof(double)));
    }}
}}

}}  // namespace bench
'''
    (BENCH / "dispatch.hpp").write_text(dispatch)

    emit_registry_tiers(registry, recipes)
    emit_registry_batch_fast(registry, recipes)
    specs = build_cydist_specs(registry, recipes)
    emit_cydist(specs)
    emit_tests(registry, recipes, specs)
    print(f"  cydist: {len(specs)} Python bindings")


def move_manual_headers() -> None:
    moves = {
        "bernoulli.hpp": "discrete/finite/bernoulli.hpp",
        "discrete_uniform.hpp": "discrete/finite/discrete_uniform.hpp",
        "binomial.hpp": "discrete/finite/binomial.hpp",
        "categorical.hpp": "discrete/finite/categorical.hpp",
        "beta_binomial.hpp": "discrete/finite/beta_binomial.hpp",
        "poisson_binomial.hpp": "discrete/finite/poisson_binomial.hpp",
        "zipf.hpp": "discrete/finite/zipf.hpp",
        "geometric.hpp": "discrete/infinite/geometric.hpp",
        "negative_binomial.hpp": "discrete/infinite/negative_binomial.hpp",
        "skellam.hpp": "discrete/infinite/skellam.hpp",
        "exponential.hpp": "continuous/semi_infinite/exponential.hpp",
        "normal.hpp": "continuous/real_line/normal.hpp",
    }
    for src, dst in moves.items():
        sp = INCLUDE / src
        dp = INCLUDE / dst
        dp.parent.mkdir(parents=True, exist_ok=True)
        if sp.exists():
            text = sp.read_text()
            dp.write_text(text)
            sp.unlink()


def apply_registry_batch_fast(recipes: dict[str, Recipe], registry: list[dict]) -> None:
    for entry in registry:
        vid = entry["id"]
        if vid not in recipes:
            continue
        bf = entry.get("batch_fast")
        if bf:
            recipes[vid].batch_fast = str(bf)


def main() -> None:
    registry = yaml.safe_load((ROOT / ".vault" / "_meta" / "registry.yaml").read_text())["distributions"]
    move_manual_headers()
    recipes = build_recipes(registry)
    apply_registry_batch_fast(recipes, registry)
    assign_sampler_tiers(recipes)
    emit_all(registry, recipes)
    with_members = sum(1 for r in recipes.values() if r.members)
    validated = sum(1 for r in recipes.values() if r.validate_body)
    print(f"Generated {len(recipes)} headers + dispatch ({len(registry)} total vault entries)")
    print(f"  validation: {validated}/{with_members} parameterized codegen recipes")


if __name__ == "__main__":
    main()
