// Generated by tools/codegen_distributions.py
#include "distributions/all.hpp"
#include "cydist_shim_span.hpp"

#include <cstddef>
#include <cstdint>
#include <vector>

extern "C" {

void cydist_benford_sample_batch(uint64_t seed, int* out, size_t n_samples) {
    distributions::Benford dist;
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_bernoulli_sample_batch(double p, uint64_t seed, int* out, size_t n_samples) {
    distributions::Bernoulli dist(p);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_beta_binomial_sample_batch(int trials, double alpha, double beta, uint64_t seed, int* out, size_t n_samples) {
    distributions::BetaBinomial dist(trials, alpha, beta);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_binomial_sample_batch(int trials, double p, uint64_t seed, int* out, size_t n_samples) {
    distributions::Binomial dist(trials, p);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_categorical_sample_batch(const double* probs, int k, uint64_t seed, int* out, size_t n_samples) {
    std::vector<double> pv(probs, probs + k);
    distributions::Categorical dist(std::move(pv));
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_hypergeometric_sample_batch(int M, int n_success, int N_draws, uint64_t seed, int* out, size_t n_samples) {
    distributions::Hypergeometric dist(M, n_success, N_draws);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_negative_hypergeometric_sample_batch(int M, int n_, int N, uint64_t seed, int* out, size_t n_samples) {
    distributions::NegativeHypergeometric dist(M, n_, N);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_poisson_binomial_sample_batch(const double* probs, int k, uint64_t seed, int* out, size_t n_samples) {
    std::vector<double> pv(probs, probs + k);
    distributions::PoissonBinomial dist(std::move(pv));
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_rademacher_sample_batch(uint64_t seed, int* out, size_t n_samples) {
    distributions::Rademacher dist;
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_soliton_sample_batch(int n_max, uint64_t seed, int* out, size_t n_samples) {
    distributions::Soliton dist(n_max);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_discrete_uniform_sample_batch(int low, int high, uint64_t seed, int* out, size_t n_samples) {
    distributions::DiscreteUniform dist(low, high);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_zipf_sample_batch(int N, double s, uint64_t seed, int* out, size_t n_samples) {
    distributions::Zipf dist(N, s);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_zipf_mandelbrot_sample_batch(int N, double q, double s, uint64_t seed, int* out, size_t n_samples) {
    distributions::ZipfMandelbrot dist(N, q, s);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_beta_negative_binomial_sample_batch(double alpha, double beta, double r, uint64_t seed, int* out, size_t n_samples) {
    distributions::BetaNegativeBinomial dist(alpha, beta, r);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_borel_sample_batch(double mu, uint64_t seed, int* out, size_t n_samples) {
    distributions::Borel dist(mu);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_conwaymaxwellpoisson_sample_batch(double lambda_, double nu, uint64_t seed, int* out, size_t n_samples) {
    distributions::Conwaymaxwellpoisson dist(lambda_, nu);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_discrete_phase_type_sample_batch(double p1, double p2, uint64_t seed, int* out, size_t n_samples) {
    distributions::DiscretePhaseType dist(p1, p2);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_delaporte_sample_batch(double lambda_, double r, double p, uint64_t seed, int* out, size_t n_samples) {
    distributions::Delaporte dist(lambda_, r, p);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_extended_negative_binomial_sample_batch(double r, double p, uint64_t seed, int* out, size_t n_samples) {
    distributions::ExtendedNegativeBinomial dist(r, p);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_floryschulz_sample_batch(double p, uint64_t seed, int* out, size_t n_samples) {
    distributions::Floryschulz dist(p);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_gausskuzmin_sample_batch(uint64_t seed, int* out, size_t n_samples) {
    distributions::Gausskuzmin dist;
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_geometric_sample_batch(double p, uint64_t seed, int* out, size_t n_samples) {
    distributions::Geometric dist(p);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_logarithmic_sample_batch(double p, uint64_t seed, int* out, size_t n_samples) {
    distributions::Logarithmic dist(p);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_mixed_poisson_sample_batch(double shape, double scale, uint64_t seed, int* out, size_t n_samples) {
    distributions::MixedPoisson dist(shape, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_negative_binomial_sample_batch(int r, double p, uint64_t seed, int* out, size_t n_samples) {
    distributions::NegativeBinomial dist(r, p);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_panjer_sample_batch(double lambda_, uint64_t seed, int* out, size_t n_samples) {
    distributions::Panjer dist(lambda_);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_parabolic_fractal_sample_batch(double b, double c, uint64_t seed, int* out, size_t n_samples) {
    distributions::ParabolicFractal dist(b, c);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_poisson_sample_batch(double mu, uint64_t seed, int* out, size_t n_samples) {
    distributions::Poisson dist(mu);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_skellam_sample_batch(double mu1, double mu2, uint64_t seed, int* out, size_t n_samples) {
    distributions::Skellam dist(mu1, mu2);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_yulesimon_sample_batch(double rho, uint64_t seed, int* out, size_t n_samples) {
    distributions::Yulesimon dist(rho);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_zeta_sample_batch(int N, double s, uint64_t seed, int* out, size_t n_samples) {
    distributions::Zeta dist(N, s);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_arcsine_sample_batch(uint64_t seed, double* out, size_t n_samples) {
    distributions::Arcsine dist;
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_argus_sample_batch(double chi, uint64_t seed, double* out, size_t n_samples) {
    distributions::Argus dist(chi);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_baldingnichols_sample_batch(double f, uint64_t seed, double* out, size_t n_samples) {
    distributions::Baldingnichols dist(f);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_bates_sample_batch(int n_, double lo, double hi, uint64_t seed, double* out, size_t n_samples) {
    distributions::Bates dist(n_, lo, hi);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_beta_sample_batch(double alpha, double beta, uint64_t seed, double* out, size_t n_samples) {
    distributions::Beta dist(alpha, beta);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_generalized_beta_sample_batch(double alpha, double beta, double lambda_, uint64_t seed, double* out, size_t n_samples) {
    distributions::GeneralizedBeta dist(alpha, beta, lambda_);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_beta_rectangular_sample_batch(double alpha, double beta, uint64_t seed, double* out, size_t n_samples) {
    distributions::BetaRectangular dist(alpha, beta);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_continuous_bernoulli_sample_batch(double lambda_, uint64_t seed, double* out, size_t n_samples) {
    distributions::ContinuousBernoulli dist(lambda_);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_continuous_binomial_sample_batch(int n_, uint64_t seed, double* out, size_t n_samples) {
    distributions::ContinuousBinomial dist(n_);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_irwinhall_sample_batch(int n_, double lo, double hi, uint64_t seed, double* out, size_t n_samples) {
    distributions::Irwinhall dist(n_, lo, hi);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_kumaraswamy_sample_batch(double a, double b, uint64_t seed, double* out, size_t n_samples) {
    distributions::Kumaraswamy dist(a, b);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_logit_normal_sample_batch(double mu, double sigma, uint64_t seed, double* out, size_t n_samples) {
    distributions::LogitNormal dist(mu, sigma);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_noncentral_beta_sample_batch(double alpha, double beta, double lam, uint64_t seed, double* out, size_t n_samples) {
    distributions::NoncentralBeta dist(alpha, beta, lam);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_pert_sample_batch(double lo, double mode, double hi, uint64_t seed, double* out, size_t n_samples) {
    distributions::Pert dist(lo, mode, hi);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_raised_cosine_sample_batch(double lo, double hi, uint64_t seed, double* out, size_t n_samples) {
    distributions::RaisedCosine dist(lo, hi);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_reciprocal_sample_batch(double a, double b, uint64_t seed, double* out, size_t n_samples) {
    distributions::Reciprocal dist(a, b);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_triangular_sample_batch(double lo, double mode, double hi, uint64_t seed, double* out, size_t n_samples) {
    distributions::Triangular dist(lo, mode, hi);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_u_quadratic_sample_batch(double a, double b, uint64_t seed, double* out, size_t n_samples) {
    distributions::UQuadratic dist(a, b);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_uniform_sample_batch(double lo, double hi, uint64_t seed, double* out, size_t n_samples) {
    distributions::Uniform dist(lo, hi);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_wigner_semicircle_sample_batch(double lo, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::WignerSemicircle dist(lo, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_benini_sample_batch(double alpha, double beta, double gamma, uint64_t seed, double* out, size_t n_samples) {
    distributions::Benini dist(alpha, beta, gamma);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_benktander_1st_kind_sample_batch(double a, double b, uint64_t seed, double* out, size_t n_samples) {
    distributions::Benktander1stKind dist(a, b);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_benktander_2nd_kind_sample_batch(double a, double b, uint64_t seed, double* out, size_t n_samples) {
    distributions::Benktander2ndKind dist(a, b);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_beta_prime_sample_batch(double alpha, double beta, uint64_t seed, double* out, size_t n_samples) {
    distributions::BetaPrime dist(alpha, beta);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_burr_sample_batch(double c, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Burr dist(c, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_chi_sample_batch(double df, uint64_t seed, double* out, size_t n_samples) {
    distributions::Chi dist(df);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_chi_squared_sample_batch(double df, uint64_t seed, double* out, size_t n_samples) {
    distributions::ChiSquared dist(df);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_noncentral_chi_squared_sample_batch(double df, double ncp, uint64_t seed, double* out, size_t n_samples) {
    distributions::NoncentralChiSquared dist(df, ncp);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_inverse_chi_squared_sample_batch(double df, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::InverseChiSquared dist(df, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_scaled_inverse_chi_squared_sample_batch(double df, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::ScaledInverseChiSquared dist(df, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_dagum_sample_batch(double c, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Dagum dist(c, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_davis_sample_batch(double nu, uint64_t seed, double* out, size_t n_samples) {
    distributions::Davis dist(nu);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_erlang_sample_batch(double a, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Erlang dist(a, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_hyper_sample_batch(double lambda1, double lambda2, double w1, uint64_t seed, double* out, size_t n_samples) {
    distributions::Hyper dist(lambda1, lambda2, w1);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_exponential_sample_batch(double rate, uint64_t seed, double* out, size_t n_samples) {
    distributions::Exponential dist(rate);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_exponential_sample_batch_f32(double rate, uint64_t seed, float* out, size_t n_samples) {
    distributions::ExponentialDistribution<float> dist(rate);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_hyperexponential_sample_batch(double lambda1, double lambda2, double w1, uint64_t seed, double* out, size_t n_samples) {
    distributions::Hyperexponential dist(lambda1, lambda2, w1);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_hypoexponential_sample_batch(double rate1, double rate2, uint64_t seed, double* out, size_t n_samples) {
    distributions::Hypoexponential dist(rate1, rate2);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_exponential_logarithmic_sample_batch(double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::ExponentialLogarithmic dist(scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_f_sample_batch(double dfn, double dfd, uint64_t seed, double* out, size_t n_samples) {
    distributions::FDistribution dist(dfn, dfd);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_noncentral_f_sample_batch(double dfn, double dfd, double nc, uint64_t seed, double* out, size_t n_samples) {
    distributions::NoncentralF dist(dfn, dfd, nc);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_folded_normal_sample_batch(double c, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::FoldedNormal dist(c, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_frechet_sample_batch(double c, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Frechet dist(c, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_gamma_sample_batch(double shape, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Gamma dist(shape, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_generalized_gamma_sample_batch(double a, double c, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::GeneralizedGamma dist(a, c, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_inverse_gamma_sample_batch(double shape, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::InverseGamma dist(shape, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_gamma_gompertz_sample_batch(double shape, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::GammaGompertz dist(shape, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_gompertz_sample_batch(double c, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Gompertz dist(c, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_shifted_sample_batch(double loc, double rate, uint64_t seed, double* out, size_t n_samples) {
    distributions::Shifted dist(loc, rate);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_half_logistic_sample_batch(double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::HalfLogistic dist(loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_half_normal_sample_batch(double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::HalfNormal dist(loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_hotellings_t_squared_sample_batch(double df1, double df2, uint64_t seed, double* out, size_t n_samples) {
    distributions::HotellingsTSquared dist(df1, df2);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_hartmanwatson_sample_batch(double nu, uint64_t seed, double* out, size_t n_samples) {
    distributions::Hartmanwatson dist(nu);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_inverse_gaussian_sample_batch(double mu, double lambda_, uint64_t seed, double* out, size_t n_samples) {
    distributions::InverseGaussian dist(mu, lambda_);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_generalized_sample_batch(double a, double c, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Generalized dist(a, c, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_kolmogorov_sample_batch(double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Kolmogorov dist(scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_levy_sample_batch(double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Levy dist(loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_log_cauchy_sample_batch(double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::LogCauchy dist(loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_log_laplace_sample_batch(double c, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::LogLaplace dist(c, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_log_logistic_sample_batch(double c, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::LogLogistic dist(c, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_log_normal_sample_batch(double mu, double sigma, uint64_t seed, double* out, size_t n_samples) {
    distributions::LogNormal dist(mu, sigma);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_log_t_sample_batch(double df, uint64_t seed, double* out, size_t n_samples) {
    distributions::LogT dist(df);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_lomax_sample_batch(double c, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Lomax dist(c, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_matrix_exponential_sample_batch(double rate1, double rate2, double rate3, uint64_t seed, double* out, size_t n_samples) {
    distributions::MatrixExponential dist(rate1, rate2, rate3);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_maxwellboltzmann_sample_batch(double a, uint64_t seed, double* out, size_t n_samples) {
    distributions::MaxwellBoltzmann dist(a);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_maxwelljuttner_sample_batch(double a, uint64_t seed, double* out, size_t n_samples) {
    distributions::Maxwelljuttner dist(a);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_mittag_leffler_sample_batch(double alpha, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::MittagLeffler dist(alpha, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_nakagami_sample_batch(double nu, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Nakagami dist(nu, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_pareto_sample_batch(double alpha, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Pareto dist(alpha, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_phase_type_sample_batch(double rate1, double rate2, double rate3, uint64_t seed, double* out, size_t n_samples) {
    distributions::PhaseType dist(rate1, rate2, rate3);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_poly_weibull_sample_batch(double shape1, double shape2, double weight, uint64_t seed, double* out, size_t n_samples) {
    distributions::PolyWeibull dist(shape1, shape2, weight);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_rayleigh_sample_batch(double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Rayleigh dist(scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_relativistic_breitwigner_sample_batch(double rho, uint64_t seed, double* out, size_t n_samples) {
    distributions::RelativisticBreitwigner dist(rho);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_rice_sample_batch(double b, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Rice dist(b, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_truncated_normal_sample_batch(double a, double b, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::TruncatedNormal dist(a, b, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_type_2_gumbel_sample_batch(double shape, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Type2Gumbel dist(shape, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_weibull_sample_batch(double shape, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Weibull dist(shape, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_discrete_weibull_sample_batch(double c, uint64_t seed, double* out, size_t n_samples) {
    distributions::DiscreteWeibull dist(c);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_wilkss_lambda_sample_batch(double a, double b, uint64_t seed, double* out, size_t n_samples) {
    distributions::WilkssLambda dist(a, b);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_cauchy_sample_batch(double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Cauchy dist(loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_exponential_power_sample_batch(double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::ExponentialPower dist(scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_fishers_z_sample_batch(double n_, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::FishersZ dist(n_, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_kaniadakis_gaussian_sample_batch(double kappa, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::KaniadakisGaussian dist(kappa, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_gaussian_q_sample_batch(double q, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::GaussianQ dist(q, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_generalized_hyperbolic_sample_batch(double p, double a, double b, uint64_t seed, double* out, size_t n_samples) {
    distributions::GeneralizedHyperbolic dist(p, a, b);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_generalized_logistic_logistic_beta_sample_batch(double c, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::GeneralizedLogisticLogisticBeta dist(c, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_generalized_normal_sample_batch(double beta, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::GeneralizedNormal dist(beta, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_geometric_stable_sample_batch(double alpha, double beta, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::GeometricStable dist(alpha, beta, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_gumbel_sample_batch(double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Gumbel dist(loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_holtsmark_sample_batch(double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Holtsmark dist(loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_hyperbolic_secant_sample_batch(double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::HyperbolicSecant dist(loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_johnsons_su_sample_batch(double a, double b, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::JohnsonsSu dist(a, b, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_landau_sample_batch(double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Landau dist(loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_laplace_sample_batch(double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Laplace dist(loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_asymmetric_sample_batch(double kappa, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Asymmetric dist(kappa, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_logistic_sample_batch(double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Logistic dist(loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_noncentral_t_sample_batch(double df, double nc, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::NoncentralT dist(df, nc, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_normal_sample_batch(double mu, double sigma, uint64_t seed, double* out, size_t n_samples) {
    distributions::Normal dist(mu, sigma);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_normal_sample_batch_f32(double mu, double sigma, uint64_t seed, float* out, size_t n_samples) {
    distributions::NormalDistribution<float> dist(mu, sigma);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_normal_inverse_gaussian_sample_batch(double a, double b, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::NormalInverseGaussian dist(a, b, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_skew_normal_sample_batch(double loc, double scale, double alpha, uint64_t seed, double* out, size_t n_samples) {
    distributions::SkewNormal dist(loc, scale, alpha);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_slash_sample_batch(double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Slash dist(loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_stable_sample_batch(double alpha, double beta, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Stable dist(alpha, beta, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_students_t_sample_batch(double df, uint64_t seed, double* out, size_t n_samples) {
    distributions::StudentT dist(df);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_tracywidom_sample_batch(double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Tracywidom dist(loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_variance_gamma_sample_batch(double a, double b, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::VarianceGamma dist(a, b, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_voigt_sample_batch(double sigma, double gamma_width, double loc, uint64_t seed, double* out, size_t n_samples) {
    distributions::Voigt dist(sigma, gamma_width, loc);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_generalized_chi_squared_sample_batch(double df1, double w1, double df2, double w2, uint64_t seed, double* out, size_t n_samples) {
    distributions::GeneralizedChiSquared dist(df1, w1, df2, w2);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_generalized_extreme_value_sample_batch(double c, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::GeneralizedExtremeValue dist(c, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_generalized_pareto_sample_batch(double c, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::GeneralizedPareto dist(c, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_marchenkopastur_sample_batch(double gamma_ratio, double sigma, uint64_t seed, double* out, size_t n_samples) {
    distributions::Marchenkopastur dist(gamma_ratio, sigma);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_kaniadakis_exponential_sample_batch(double kappa, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::KaniadakisExponential dist(kappa, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_kaniadakis_gamma_sample_batch(double kappa, double shape, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::KaniadakisGamma dist(kappa, shape, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_kaniadakis_weibull_sample_batch(double kappa, double shape, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::KaniadakisWeibull dist(kappa, shape, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_kaniadakis_logistic_sample_batch(double kappa, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::KaniadakisLogistic dist(kappa, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_kaniadakis_erlang_sample_batch(double kappa, double shape, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::KaniadakisErlang dist(kappa, shape, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_q_exponential_sample_batch(double q, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::QExponential dist(q, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_q_gaussian_sample_batch(double q, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::QGaussian dist(q, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_q_weibull_sample_batch(double q, double shape, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::QWeibull dist(q, shape, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_shifted_log_logistic_sample_batch(double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::ShiftedLogLogistic dist(scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_tukey_lambda_sample_batch(double lam, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::TukeyLambda dist(lam, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_rectified_gaussian_sample_batch(double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::RectifiedGaussian dist(loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_ewens_sample_batch(double theta, int n_, uint64_t seed, double* out, size_t n_samples) {
    distributions::Ewens dist(theta, n_);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_multinomial_sample_batch(int n_, double p0, uint64_t seed, double* out, size_t n_samples) {
    distributions::Multinomial dist(n_, p0);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_dirichlet_multinomial_sample_batch(int n_, double a0, double a1, double a2, uint64_t seed, double* out, size_t n_samples) {
    distributions::DirichletMultinomial dist(n_, a0, a1, a2);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_negative_multinomial_sample_batch(double r, double p0, double p1, double p2, uint64_t seed, double* out, size_t n_samples) {
    distributions::NegativeMultinomial dist(r, p0, p1, p2);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_dirichlet_sample_batch(double a0, double a1, double a2, uint64_t seed, double* out, size_t n_samples) {
    distributions::Dirichlet dist(a0, a1, a2);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_generalized_dirichlet_sample_batch(double a1, double b1, double a2, double b2, uint64_t seed, double* out, size_t n_samples) {
    distributions::GeneralizedDirichlet dist(a1, b1, a2, b2);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_multivariate_laplace_sample_batch(double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::MultivariateLaplace dist(scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_multivariate_normal_sample_batch(double rho, uint64_t seed, double* out, size_t n_samples) {
    distributions::MultivariateNormal dist(rho);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_multivariate_stable_sample_batch(double alpha, double beta, uint64_t seed, double* out, size_t n_samples) {
    distributions::MultivariateStable dist(alpha, beta);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_multivariate_t_sample_batch(double df, uint64_t seed, double* out, size_t n_samples) {
    distributions::MultivariateT dist(df);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_normal_gamma_sample_batch(double shape, double rate, uint64_t seed, double* out, size_t n_samples) {
    distributions::NormalGamma dist(shape, rate);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_normal_inverse_gamma_distribution_sample_batch(double shape, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::NormalInverseGammaDistribution dist(shape, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_lkj_sample_batch(double eta, uint64_t seed, double* out, size_t n_samples) {
    distributions::Lkj dist(eta);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_matrix_beta_sample_batch(double a, double b, uint64_t seed, double* out, size_t n_samples) {
    distributions::MatrixBeta dist(a, b);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_matrix_f_sample_batch(double df1, double df2, double v00, double v11, uint64_t seed, double* out, size_t n_samples) {
    distributions::MatrixF dist(df1, df2, v00, v11);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_matrix_normal_sample_batch(double row_var, double col_var, uint64_t seed, double* out, size_t n_samples) {
    distributions::MatrixNormal dist(row_var, col_var);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_matrix_t_sample_batch(double df, double row_var, double col_var, uint64_t seed, double* out, size_t n_samples) {
    distributions::MatrixT dist(df, row_var, col_var);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_matrix_gamma_sample_batch(double shape, double v00, double v11, uint64_t seed, double* out, size_t n_samples) {
    distributions::MatrixGamma dist(shape, v00, v11);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_inverse_matrix_gamma_distribution_sample_batch(double shape, double v00, double v11, uint64_t seed, double* out, size_t n_samples) {
    distributions::InverseMatrixGammaDistribution dist(shape, v00, v11);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_wishart_sample_batch(double df, double v00, double v01, double v11, uint64_t seed, double* out, size_t n_samples) {
    distributions::Wishart dist(df, v00, v01, v11);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_normal_wishart_sample_batch(double df, double kappa, double v00, double v11, uint64_t seed, double* out, size_t n_samples) {
    distributions::NormalWishart dist(df, kappa, v00, v11);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_inverse_wishart_sample_batch(double df, double v00, double v01, double v11, uint64_t seed, double* out, size_t n_samples) {
    distributions::InverseWishart dist(df, v00, v01, v11);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_normal_inverse_sample_batch(double df, double kappa, double v00, double v11, uint64_t seed, double* out, size_t n_samples) {
    distributions::NormalInverse dist(df, kappa, v00, v11);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_complex_sample_batch(double df, double v00, double v11, uint64_t seed, double* out, size_t n_samples) {
    distributions::Complex dist(df, v00, v11);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_uniform_distribution_on_a_stiefel_manifold_sample_batch(uint64_t seed, double* out, size_t n_samples) {
    distributions::UniformDistributionOnAStiefelManifold dist;
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_circular_uniform_sample_batch(double mu, double kappa, uint64_t seed, double* out, size_t n_samples) {
    distributions::CircularUniform dist(mu, kappa);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_univariate_von_mises_sample_batch(double mu, double kappa, uint64_t seed, double* out, size_t n_samples) {
    distributions::UnivariateVonMises dist(mu, kappa);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_wrapped_normal_sample_batch(double mu, double sigma, uint64_t seed, double* out, size_t n_samples) {
    distributions::WrappedNormal dist(mu, sigma);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_wrapped_cauchy_sample_batch(double c, double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::WrappedCauchy dist(c, loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_wrapped_exponential_sample_batch(double loc, double rate, uint64_t seed, double* out, size_t n_samples) {
    distributions::WrappedExponential dist(loc, rate);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_wrapped_asymmetric_laplace_sample_batch(double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::WrappedAsymmetricLaplace dist(loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_wrapped_levy_sample_batch(double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::WrappedLevy dist(loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_kent_sample_batch(double kappa, double beta, uint64_t seed, double* out, size_t n_samples) {
    distributions::Kent dist(kappa, beta);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_bivariate_von_mises_sample_batch(double kappa1, double kappa2, uint64_t seed, double* out, size_t n_samples) {
    distributions::BivariateVonMises dist(kappa1, kappa2);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_von_misesfisher_sample_batch(double kappa, uint64_t seed, double* out, size_t n_samples) {
    distributions::VonMisesfisher dist(kappa);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_bingham_sample_batch(double kappa, uint64_t seed, double* out, size_t n_samples) {
    distributions::Bingham dist(kappa);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_dirac_delta_function_sample_batch(double x0, uint64_t seed, double* out, size_t n_samples) {
    distributions::DiracDelta dist(x0);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}

void cydist_cantor_sample_batch(double loc, double scale, uint64_t seed, double* out, size_t n_samples) {
    distributions::Cantor dist(loc, scale);
    distributions::Pcg32 rng(seed);
    cydist_shim::sample_batch(dist, out, n_samples, rng);
}
}  // extern "C"
